<a href="https://colab.research.google.com/github/dasom222g/numpy-test/blob/main/01_NumPy_%E1%84%89%E1%85%B5%E1%86%AF%E1%84%89%E1%85%B3%E1%86%B8_%E1%84%8F%E1%85%A9%E1%84%83%E1%85%B3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 데이터 분석을 위한 패키지

## 1. 배열 데이터를 효과적으로 다루는 NumPy

### 넘파이 연습 사이트: https://www.machinelearningplus.com/python/101-numpy-exercises-python/

### 1.1 넘파이 모듈 불러오기

In [2]:
import numpy as np

np.__version__

'1.26.4'

### 1.2 배열 생성하기

In [6]:
np.array([123])

array([123])

#### 시퀀스 데이터로부터 1차원 배열 생성

In [ ]:
import numpy as np

data1 = [0, 1, 2, 3, 4, 5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [ ]:
# Q. data1과 a1의 데이터 타입 확인해보기 <힌트: type()>
print(type(data1))
print(type(a1))

<class 'list'>
<class 'numpy.ndarray'>


In [11]:
# list는 실수와 정수 공존 가능하지만 넘파이는 공존 불가하여 정수도 실수로 변환
data2 = [1, 2, 4]
a2 = np.array(data2)
a2.dtype

dtype('int64')

In [ ]:
# list는 실수와 정수 공존 가능하지만 넘파이는 공존 불가하여 정수도 실수로 변환
# 넘파이는 수치계산에 특화된 라이브러기이기 때문
data2 = [0.1, 5, 4, 12, 0.5]
a2 = np.array(data2)
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [ ]:
# array를 이루고있는 요소들의 타입 확인(dtype)
a1.dtype

dtype('int64')

In [ ]:
a2.dtype

dtype('float64')

#### array( )에 리스트 데이터를 직접 넣어서 배열 객체를 생성

In [12]:
np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
np.array([0.5, 2, 0.01, 8])

array([0.5 , 2.  , 0.01, 8.  ])

In [ ]:
np.array([[1,2,3], [4,5,6], [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### 범위를 지정해 배열 생성

**arr_obj = np.arange(start, stop, step)** <br>
→ **start부터 시작해서 stop 전까지 step만큼 계속 더해 배열 생성**

In [20]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [ ]:
# range()와 같은 규칙
np.arange(1, 10) # np.arange(1, 10, 1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5) # np.arange(0, 5, 1)

array([0, 1, 2, 3, 4])

In [27]:
# Q. arange()를 사용하여 array([4, 6, 8, 10, 12, 14]) 배열을 만들어보기
# 아래에 코드를 작성하세요
np.arange(4, 15, 2)

array([ 4,  6,  8, 10, 12, 14])

In [49]:
# Q. arange()를 사용하여 array([4, 6, 8, 10, 12, 14]) 배열을 만들어보기
# 아래에 코드를 작성하세요

arr = np.arange(4, 15, 2)

In [54]:
# 1차원 배열을 reshape()을 이용해 2차원 배열로 변경
np.arange(1, 10).reshape(3, 3)

np.arange(12).reshape(3, 4)

np.arange(12).reshape(3, 4).shape

(3, 4)

In [ ]:
# 1차원 배열을 reshape()을 이용해 2차원 배열로 변경
np.arange(12).reshape(4, 3) # 행, 열 갯수

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
b1 = np.arange(12).reshape(4, 3)
b1.shape

(4, 3)

In [ ]:
# n개의 요소를 갖는 1차원 배열의 shape은 (n,)로 표시된다.
b2 = np.arange(5)
b2.shape

(5,)

#### 범위의 시작과 끝을 지정하고 데이터의 개수를 지정해 Numpy 배열 생성 linspace( )
- 시작값과 끝값을 지정한 개수만큼 균등하게 나눈 배열 생성
- linspace(시작값, 끝값, 갯수)

In [64]:
arr3 = np.linspace(1, 10, 30)
# len(arr3)
arr3

array([ 1.        ,  1.31034483,  1.62068966,  1.93103448,  2.24137931,
        2.55172414,  2.86206897,  3.17241379,  3.48275862,  3.79310345,
        4.10344828,  4.4137931 ,  4.72413793,  5.03448276,  5.34482759,
        5.65517241,  5.96551724,  6.27586207,  6.5862069 ,  6.89655172,
        7.20689655,  7.51724138,  7.82758621,  8.13793103,  8.44827586,
        8.75862069,  9.06896552,  9.37931034,  9.68965517, 10.        ])

In [ ]:
np.linspace(1, 10, 10) # 시작, 마지막 값, 갯수

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [67]:
np.linspace(0, np.pi, 20 )
np.pi

3.141592653589793

#### 특별한 형태의 배열 생성
**<결과를 보고 어떤 메소드인지 추측해보자!>**

In [71]:
# 0으로 채우기

np.zeros(3)
np.zeros(9).reshape(3, 3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [73]:
# 1로 채우기
np.ones(6).reshape(2, 3)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [76]:
# 단위행렬로 5, 5 배열 만들기
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.zeros(10) # 0으로 갯수만큼 채우기

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,4)) # 0으로 3행 4열 채우기

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(5) # 1로 갯수만큼 채우기

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.eye(5) # 단위행렬 (5x5)
# 대각선이 1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 1.3 배열의 데이터 타입 변환

In [84]:
# 아래 배열을 실수로 형변환하기
str_a1 = np.array(['1.567', '0.123', '5.123', '9', '8'])
num_a1 = str_a1.astype(float)
str_a1.dtype, num_a1.dtype

(dtype('<U5'), dtype('float64'))

In [88]:
num_list = np.array([1.12, 3.14, 5.86])
num_list = num_list.astype(int)
num_list, num_list.dtype

(array([1, 3, 5]), dtype('int64'))

In [ ]:
# dtype = '<U8'은 데이터의 형식이 유니코드이며 문자의 수는 최대 8개라는 것을 의미
# U: 문자열
# 8: 요소중 가장 긴 문자열의 갯수로 n자리 문자열을 담았다는 의미
np.array(['1.5', '0.62', '2', '3.14', '3.141592'])

array(['1.5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

In [ ]:
str_a1 = np.array(['1.567', '0.123', '5.123', '9', '8'])
num_a1 = str_a1.astype(float) # Numpy 배열의 형 변환
num_a1

array([1.567, 0.123, 5.123, 9.   , 8.   ])

In [ ]:
str_a1.dtype

dtype('<U5')

In [ ]:
num_a1.dtype

dtype('float64')

In [ ]:
str_a2 = np.array(['1', '3', '5', '7', '9'])
num_a2 = str_a2.astype(int)
num_a2

array([1, 3, 5, 7, 9])

In [ ]:
str_a2.dtype

dtype('<U1')

In [ ]:
num_a2.dtype

dtype('int64')

In [87]:
# Q. 어떤 결과가 나올지 예측해보기
num_f1 = np.array([10, 21, 0.549, 4.75, 5.98])
num_i1 = num_f1.astype(int) # 소수점은 버림
num_i1

array([10, 21,  0,  4,  5])

In [ ]:
num_f1.dtype

dtype('float64')

In [ ]:
num_i1.dtype

dtype('int64')

### 1.4 난수 배열의 생성

In [12]:
# 랜덤 숫자 생성
np.random.rand(2, 3)

array([[0.0403212 , 0.77809339, 0.64887758],
       [0.87099242, 0.88595392, 0.81618521]])

In [ ]:
# rand(): [0. 1) 사이의 실수 난수를 갖는 넘파이 배열 생성

np.random.rand(2,3) # 2 x 3의 2차원 배열의 실수 난수 생성

array([[0.92384499, 0.82369026, 0.92870186],
       [0.90420224, 0.58788516, 0.12008253]])

In [17]:
a = np.random.rand(1) # 사이즈를 입력하지 않으면 1로 간주
a

array([0.75558804])

In [ ]:
np.random.rand(2,3,4) # 3차원

array([[[0.71304727, 0.12760328, 0.88253148, 0.15323534],
        [0.27935776, 0.2452722 , 0.6645442 , 0.65875127],
        [0.5577089 , 0.64975905, 0.07422378, 0.68700157]],

       [[0.69905723, 0.2651267 , 0.06968332, 0.57024931],
        [0.83741069, 0.0936674 , 0.83379752, 0.93905042],
        [0.42266996, 0.52726699, 0.7937363 , 0.55499841]]])

In [21]:
np.random.randint(1, 11, size=(1, 10))

array([[ 3, 10,  9,  9,  1, 10,  3,  8,  1,  3]])

In [19]:
np.random.randint(10, 20, size=(3, 3))

array([[15, 16, 14],
       [16, 15, 12],
       [16, 10, 10]])

In [ ]:
# randint(): 지정한 범위에 해당하는 정수로 난수 배열을 생성
# 시작값이 0이면 생략가능
np.random.randint(10, size=(3, 4)) # 0부터 9까지

array([[9, 9, 2, 9],
       [4, 2, 5, 0],
       [8, 5, 8, 3]])

In [ ]:
np.random.randint(1, 30, size=(3, 4))

array([[ 7,  9,  1, 15],
       [10, 12, 22, 17],
       [10, 20, 26, 21]])

### 1.5 배열의 연산

#### 기본 연산

In [ ]:
# 넘파이 배열의 연산을 살펴보기 전에... 리스트끼리도 연산이 되나요?
lst1 = [10, 20, 30, 40]
lst2 = [1, 2, 3, 4]
lst1 + lst2

[10, 20, 30, 40, 1, 2, 3, 4]

In [45]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

arr1 + arr2
arr1 - arr2
arr2 / arr1
arr1 * arr2
arr2 ** 2
(arr1 / arr2 ** 2).dtype

arr1 > 20 # boolean배열 리턴
arr1[arr1 > 20] #  조건에 맞는 요소들 뽑아서 리턴


array([30, 40])

In [ ]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

**아래 연산 식에 대해 먼저 결과값을 예측해보고 직접 실행해보기**

In [ ]:
arr1 + arr2

array([11, 22, 33, 44])

In [ ]:
arr1 - arr2

array([ 9, 18, 27, 36])

In [ ]:
arr2 * 2

array([2, 4, 6, 8])

In [ ]:
arr2 ** 2

array([ 1,  4,  9, 16])

In [ ]:
arr1 * arr2

array([ 10,  40,  90, 160])

In [ ]:
arr1 / arr2

array([10., 10., 10., 10.])

In [ ]:
arr1 / (arr2 ** 2)

array([10.        ,  5.        ,  3.33333333,  2.5       ])

In [ ]:
arr1 > 20 # 요소별로 비교하여 배열로 리턴

array([False, False,  True,  True])

In [ ]:
arr1[arr1 > 20] # true인 요소만 리턴

array([30, 40])

In [ ]:
# 벡터 행렬: 각 요소별로 곱한다음 더한값으로 무조건 갯수는 1개만 나옴
# 벡터: 숫자 여러개가 한줄로 나열된것 ([10, 20, 30, 40]) [1차원]
# 스칼라: 숫자 한개 [0차원]
# 매트릭스: 여러개의 벡터 [2차원 텐서]
# 벡터, 스칼라, 매트릭스를 모두 다 '텐서'라고 함

# 이미지는 4차원 텐서 - 면이기 때문에 2차원, rgb로 컬로 표현해서 +1차원, 여러개의 이미지라 배열로 관리하니 +1차원
arr1 @ arr2 # [10, 20, 30, 40] @ [1, 2, 3, 4]

300

### 1.6 통계를 위한 연산

In [13]:
arr3 = np.arange(1, 6)
arr3

# 배열의 합과 평균
arr3.sum(), arr3.mean()

# 배열의 표준편차와 분산
arr3.std(), arr3.var()

# 배열의 최솟값, 최댓값
arr3.min(), arr3.max()

# 배열의 누적 합 구하기
arr3.cumsum()

# 배열의 누적 곱 구하기
arr3.cumprod()

(1.4142135623730951, 2.0)

In [ ]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [ ]:
# 배열의 합과 평균
[arr3.sum(), arr3.mean()]

[10, 2.0]

In [ ]:
# 배열의 표준편차와 분산
[arr3.std(), arr3.var()]

[1.4142135623730951, 2.0]

In [ ]:
# 배열의 최솟값, 최댓값
[arr3.min(), arr3.max()]

[0, 4]

In [ ]:
arr4 = np.arange(1,5)
arr4

array([1, 2, 3, 4])

In [ ]:
# 배열의 누적 합 구하기
arr4.cumsum()

array([ 1,  3,  6, 10])

In [ ]:
# 배열의 누적 곱 구하기
arr4.cumprod()

array([ 1,  2,  6, 24])

arr1 = np.arange(4).reshape(2, 2)
arr2 = np.arange(5, 11).reshape(2, 3)

arr1, arr2

### 1.7 행렬 연산

In [21]:
arr1 = np.arange(4).reshape(2, 2)
arr2 = np.arange(4, 10).reshape(2, 3)

arr1, arr2

(array([[0, 1],
        [2, 3]]),
 array([[4, 5, 6],
        [7, 8, 9]]))

In [27]:
# 내적곱
np.dot(arr1, arr2)

arr1 @ arr2

arr1.dot(arr2)

# 행과 열 교환
np.transpose(arr1), arr2.T

(array([[0, 2],
        [1, 3]]),
 array([[4, 7],
        [5, 8],
        [6, 9]]))

In [ ]:
A = np.array([0, 1, 2, 3]).reshape(2,2)
A

In [ ]:
B = np.array([3, 2, 0, 1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

In [ ]:
# 행렬 간의 내적 구하는 방법1
# 내적곱이 뭐야..
# 행과 열을 벡터곱
A.dot(B)

array([[0, 1],
       [6, 7]])

In [ ]:
# 행렬 간의 내적 구하는 방법2
np.dot(A,B)

array([[0, 1],
       [6, 7]])

In [ ]:
C = np.array([3, 6, 9, 1, 2, 3]).reshape(3,2)
# 열과 행의 갯수가 맞지않아서 에러
np.dot(B,C)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [ ]:
np.dot(C,B)

array([[ 9, 12],
       [27, 19],
       [ 6,  7]])

In [ ]:
# 행렬 A의 전치행렬 구하기
# 대각으로 값 교체, 수직->수평, 수평->수직으로 변형할때도 사용
np.transpose(A)

A.T # 동일

array([[0, 2],
       [1, 3]])

In [ ]:
A.transpose()

array([[0, 2],
       [1, 3]])

In [ ]:
A

array([[0, 1],
       [2, 3]])

In [ ]:
# 행렬 A의 역행렬 구하기
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [ ]:
# 행렬 A의 행렬식 구하기
# 몰라도 됨
np.linalg.det(A)

-2.0

### 1.8 배열의 인덱싱과 슬라이싱
- 인덱싱(Indexing): 배열의 위치나 조건을 지정해 배열의 원소를 선택하는 것
- 슬라이싱(Slicing): 범위를 지정해 배열의 원소를 선택하는 것

#### 배열의 인덱싱

In [28]:
# 1차원 배열 인덱싱 <배열명[위치]>
# 배열 원소의 위치는 0부터 시작
a1 = np.array([0, 10, 20, 30, 40, 50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [ ]:
a1[0]

0

In [ ]:
a1[4]

40

In [ ]:
a1[5] = 70
a1

array([ 0, 10, 20, 30, 40, 70])

In [ ]:
# Q. 아래 코드를 실행시키면 어떤 결과가 나올까?
a1[6] = 90 # 추가는 안됨

IndexError: index 6 is out of bounds for axis 0 with size 6

In [30]:
a1[a1 > 20]

array([30, 40, 50])

In [ ]:
# 그룹 인덱싱
a1[[1,3,4]] # 1번째, 3번째, 4번째 값 뽑기

array([10, 30, 40])

In [14]:
# 2차원 배열 인덱싱 <배열명[행_위치, 열_위치]>
a2 = np.arange(10, 100, 10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [17]:
# 행열 간단하게 사용
a2[0, 1]

# 그룹 인덴싱
a2[[0, 1]]

# 그룹 값 변경
# a2[0] = np.array([11, 22, 33])

# Q. 출력값이 array([10, 80])이 나오도록 a2를 가지고 인덱싱해보기

[a2[0, 0], a2[2, 1]]

a2[[0, 0], [2, 1]]

# a2

array([30, 20])

In [19]:
# Q. 숫자 1부터 20을 원소로 갖는 배열 안에서 조건을 지정해서 2의 배수인 원소만 선택하기
b = np.arange(1, 21)

result = b[b % 2 == 0]
result

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [3]:
# 2차원 배열 인덱싱 <배열명[행_위치, 열_위치]>
a2 = np.arange(10, 100, 10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
a2[0, 2] # 0행 2열,  a2[0][2] 와 동일

30

In [ ]:
a2[2, 2]

90

In [ ]:
# a2의 90이라는 숫자를 95로 바꾸고 싶으면 어떻게 해야할까?
# 아래에 코드를 작성해보세요
a2[2, 2] = 95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [ ]:
# 열_위치없이 배열명[행_위치]만 입력하면 지정한 행 전체가 선택됨
a2[1]

array([40, 50, 60])

In [ ]:
# 그룹으로 값 변경
a2[1] = np.array([45, 55, 65])
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 95]])

In [ ]:
# 그룹으로 값 변경
a2[1] = [47, 57, 67]
a2

array([[10, 20, 30],
       [47, 57, 67],
       [70, 80, 95]])

In [ ]:
# Q. 출력값이 array([10, 80])이 나오도록 a2를 가지고 인덱싱해보기

a2

# np.array([a2[0, 0], a2[2, 1]])

[a2[0, 0], a2[2, 1]]

# or
a2[[0, 2], [0, 1]] # 첫번째 리스트: 행 인덱스, 두번째 리스트: 열 인덱스


array([10, 80])

In [ ]:
# 조건을 지정해 조건에 맞는 배열의 원소만 선택하기
a = np.array([1, 2, 3, 4, 5, 6])
a[a > 3]

array([4, 5, 6])

In [ ]:
# Q. 숫자 1부터 20을 원소로 갖는 배열 안에서 조건을 지정해서 2의 배수인 원소만 선택하기
b = np.arange(1, 21)
b[b % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

#### 배열의 슬라이싱

In [28]:
# 1차원 배열
# 그룹으로 변경
arr1 = np.array([1, 2, 3, 4, 5])

arr1[:3]

# 슬라이싱한 데이터 일괄 변경
arr1[1:3] = 10

arr1


array([ 1, 10, 10,  4,  5])

In [40]:
# 2차원 배열 슬라이싱

# Q. 아래 결과가 나오도록 b2를 가지고 인덱싱해보기
'''
array([[20, 30],
       [50, 60],
       [80, 90]])
'''

arr2 = np.arange(10, 100, 10).reshape(3, 3)
arr2




array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [46]:
arr2[: 2]

arr2[:, 1:3] # 행, 렬 슬라이싱

# 값 변경
arr2[:, 1:3] = np.array([[1, 2], [3, 4], [5, 6]])
arr2

array([[10,  1,  2],
       [40,  3,  4],
       [70,  5,  6]])

In [21]:
b1 = np.array([0, 10, 20, 30, 40, 50])
b1[1:4]
b1

array([ 0, 10, 20, 30, 40, 50])

In [ ]:
b1[:3]

array([ 0, 10, 20])

In [ ]:
b1[2:]

array([20, 30, 40, 50])

In [ ]:
b1[2:5] = np.array([25, 35, 45])
b1

array([ 0, 10, 25, 35, 45, 50])

In [ ]:
# 슬라이싱한 값들 하나로 일괄 변경

b1[3:6] = 60
b1

array([ 0, 10, 20, 60, 60, 60])

In [43]:
b2 = np.arange(10, 100, 10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
b2[1:3, 1:] # 행과 열

array([[50, 60],
       [80, 90]])

In [ ]:
# Q. 아래 결과가 나오도록 b2를 가지고 인덱싱해보기
'''
array([[20, 30],
       [50, 60],
       [80, 90]])
'''

b2[:, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [44]:
# Q. 이 코드는 어떤 결과를 출력할지 추측해보기
b2[1][0:2]

array([40, 50])

In [45]:
# Q. 아래 코드는 어떤 결과를 출력할지 추측해보기
b2[0:2, 1:3] = np.array([[25, 35], [55, 65]])
b2


array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])

In [ ]:
ex = np.array([1, 2, 0, 0, 4, 0])
ex[ex != 0]

array([1, 2, 4])

### 1.9 이 외에도 알아두면 좋은 넘파이 함수

#### 조건에 맞는 인덱스 찾기

In [54]:
a = np.arange(10, 20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [61]:

np.where(a > 14) # 인덱스 번호


# 정렬 랜덤 ⭐️
np.random.shuffle(a)
print(a)


# 최대값 인덱스 추출
np.argmax(a), np.argmin(a)
# 최소값 인덱스 추출


# 제일 작은값 부터 순서대로 인덱스 찾기
np.argsort(a)

[12 15 18 17 16 10 13 19 11 14]


array([5, 8, 0, 6, 9, 1, 4, 3, 2, 7])

In [ ]:
# np.where() ⭐️
a = np.arange(10, 20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.where(a > 15)

(array([6, 7, 8, 9]),)

In [ ]:
# np.argmax(), np.argmin()
np.argmax(a) # 최대값 인덱스 찾기⭐️

9

In [ ]:
np.argmin(a) # 최소값 인덱스 찾기⭐️

0

In [ ]:
# np.argsort(): 작은 값부터 순서대로 인덱스 반환
b = np.arange(1, 5)
np.random.shuffle(b) # 정렬 랜덤 ⭐️
b

array([2, 3, 1, 4])

In [ ]:
np.argsort(b) # 제일 작은값 부터 순서대로 인덱스 찾기

array([2, 0, 1, 3])

In [ ]:
# Q. 반대로 내림차순으로 인덱스를 반환하고 싶으면??
np.argsort(b)[::-1]

array([3, 1, 0, 2])

##### 넘파이 실습 문제 - 아래 문제를 직접 풀어보세요!
1. Import the numpy package under the name np
2. Create a 3X3 matrix with values ranging from 0 to 8
3. Find indices of non-zero elements from [1, 2, 0, 0, 4, 0]
4. Create a 10X10 array with random values and find the minimum and maximum values
5. Find an index of minimum element from [34, 25, 23, 18, 30, 40, 37]

In [ ]:
# 1
import numpy as np

# 2
arr = np.arange(9).reshape(3, 3) # 3행 3열
# print(arr)

#3
arr2 = np.array([1, 2, 0, 0, 4, 0])
no_zero_indexs = np.where(arr2 !=0)
# print(no_zero_indexs) # 배열안의 배열로 리턴
# np.where(arr2 !=0)[0]
#4
arr3 = np.random.randint(1, 51, size=(10, 10))
# print(arr3)
# print(arr3.min(), arr3.max()) # 배열의 최소값, 최대값 찾기

#5
arr4 = np.array([34, 25, 23, 18, 30, 40, 37])
np.argmin(arr4) # 최소값의 인덱스찾기



3